apiVersion: v1
data:
  database-name: cGV0Y2xpbmlj
  database-password: cGV0Y2xpbmlj
  database-root-password: cGV0Y2xpbmlj
  database-user: cGV0Y2xpbmlj
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2021-04-22T01:50:09Z"
  labels:
    app: mysql-ephemeral
    app.kubernetes.io/component: mysql-ephemeral
    app.kubernetes.io/instance: mysql-ephemeral
    template: mysql-ephemeral-template
  name: mysql
type: Opaque
